# Usa imagem oficial do Node.js
FROM node:18

# Cria e define diretório de trabalho
WORKDIR /app

# Copia os arquivos package.json e package-lock.json
COPY package*.json ./

# Instala dependências
RUN npm install

# Copia o restante do código
COPY . .

# Expõe a porta que o Apollo Server vai usar
EXPOSE 5000

# Comando para iniciar o servidor, agora apontando para o arquivo index.js em src
CMD ["node", "src/index.js"]
