version: "3.8"

services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    networks:
      - projeto_de_usuarios_network
    environment:
      - POSTGRES_PASSWORD=852
    volumes:
      - projeto_de_usuarios_postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - projeto_de_usuarios_network
    depends_on:
      - db

  backend-graphql:
    volumes:
      - ./backend-GraphQL:/app
    build:
      context: ./backend-GraphQL
      dockerfile: Dockerfile
    container_name: backend-graphql
    ports:
      - "5000:5000"
    networks:
      - projeto_de_usuarios_network
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4000:4000"
    networks:
      - projeto_de_usuarios_network

  frontend-react:
    build: ./frontend-react
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ./frontend-react:/app
    command: npm run dev -- --host
    networks:
      - projeto_de_usuarios_network

networks:
  projeto_de_usuarios_network:
    driver: bridge

volumes:
  projeto_de_usuarios_postgres_data:
